### ISSUE TITLE
Add cache support for FileSystemBackend

### ISSUE THREAD

**Issue by sergiodxa** [sergiodxa/remix-i18next#1]
Right now the backend doesn’t cache the translations loaded, so on every navigation you could load again a translation you already loaded.

The FileSystemBackend should have a way to pass a cache, with an in-memory default cache, so you can pass them.

In development the cache should be avoided so you can update your JSON files, navigate or reload and get the new translations.

**Comment by Nettsentrisk** [comment]
> In development the cache should be avoided so you can update your JSON files, navigate or reload and get the new translations.

This doesn't seem to work? Anything that you have to do in particular to make that work?

**Comment by sergiodxa** [comment]
Custom backends were removed long time ago, current version of remix-i18next uses normal i18next backends so any caching should happen there and outside remix-i18next scope.
