### ISSUE TITLE
Add FetchBackend example

### ISSUE THREAD

**Issue by sergiodxa** [sergiodxa/remix-i18next#11]

**Comment by matmilbury** [comment]
If you want, I can add an example with locize.com backend because that's what we use at https://www.tenset.io/ 🙂

**Comment by adrai** [comment]
@matmilbury like this one? https://github.com/locize/locize-remix-i18next-example

**Comment by matmilbury** [comment]
Something like that one 👍

**Comment by sergiodxa** [comment]
Custom backends are not a thing since v4.0.0, you can use any i18next backend.
