### ISSUE TITLE
getFixedT not working on cloned Request

### ISSUE THREAD

**Issue by tomer-rmor** [sergiodxa/remix-i18next#119]
### Describe the bug

```
//somewhere in the code
const remixI18next = new RemixI18Next({..});

export async function action({ request, context }: ActionArgs) {
   const req = request.clone();
   const t = remixI18next.getFixedT(req); // Throw error
```

after debugging i found the problem.
in https://github.com/sergiodxa/remix-i18next/blob/main/src/lib/get-client-locales.ts
in the function getHeaders
'requestOrHeaders instanceof Request ' doest work on cloned request
I think it can also considered to be a bug in Remix

### Your Example Website or App

https://stackblitz.com/edit/remix-run-remix-5cvpyv?file=app/routes/index.tsx

### Steps to Reproduce the Bug or Issue

NA

### Expected behavior

should not throw

### Platform

NA

**Comment by tomer-yechiel** [comment]
will be fixed once https://github.com/remix-run/remix/pull/5566/files will be merged
