### ISSUE TITLE
Add FileSystemBackend example

### ISSUE THREAD

**Issue by sergiodxa** [sergiodxa/remix-i18next#12]

**Comment by valerius21** [comment]
any progress on this issue? I am still kinda unsure on how I should refactor my `translations.ts` file :)

**Comment by valerius21** [comment]
I got it working. The screenshot below should explain how it's structured if anyone is interested. Thanks for the incredible work @sergiodxa ! :)

![image](https://user-images.githubusercontent.com/10323945/152651920-485c87d5-e2c4-4a3c-9ae8-7874790d592b.png)

**Comment by adrai** [comment]
I made an example here: https://github.com/adrai/my-remix-app/blob/main/app/i18n.server.js

**Comment by sergiodxa** [comment]
Custom backends are not a thing since v4.0.0, you can use any i18next backend.

**Comment by adrai** [comment]
Awesome... did just update the blog post(s): https://locize.com/blog/remix-i18n/
