### ISSUE TITLE
i18next busts up defer in Remix

### ISSUE THREAD

**Issue by janhesters** [sergiodxa/remix-i18next#125]
### Describe the bug

When you use the `useTranslation` hook in a component that renders `Suspense`, you get the following error in your console:

```
Uncaught Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.
```

### Your Example Website or App

No website

### Steps to Reproduce the Bug or Issue

Use a simple `<Suspense />`  boundary for [Streaming](https://remix.run/docs/en/1.15.0/guides/streaming#enable-react-18-streaming) with i18next Remix and you get the error.

```tsx
import type { LoaderArgs } from '@remix-run/node'; // or cloudflare/deno
import { defer } from '@remix-run/node'; // or cloudflare/deno
import { Await, useLoaderData } from '@remix-run/react';
import { Suspense } from 'react';
import { useTranslation } from 'react-i18next';

export const loader = async ({}: LoaderArgs) => {
  const critical = await new Promise(resolve =>
    setTimeout(() => resolve('hello'), 1000),
  );
  const nonCricital = new Promise(resolve =>
    setTimeout(() => resolve('world'), 5000),
  );

  return defer({ critical, nonCricital });
};

export default function PackageRoute() {
  const data = useLoaderData<typeof loader>();
  const { t } = useTranslation(); // ❗️ Remove this and the error goes away.

  return (
    <main>
      <h1>Let's locate your package</h1>
      <p>{data.critical}</p>
      <Suspense fallback={<p>Loading package location...</p>}>
        <Await
          resolve={data.nonCricital}
          errorElement={<p>Error loading package location!</p>}
        >
          {nonCricital => <p>{nonCricital}</p>}
        </Await>
      </Suspense>
    </main>
  );
}
```

Adding namespaces (e.g. `export const handle = { i18next: 'foo' };`) doesn't alter the result.

### Expected behavior

I expected no error and everything to work fine.

### Platform

- OS: macOS
- Browser: Chrome & Safari & Firefox
- Version: 111.0.5563.146

**Comment by sergiodxa** [comment]
This seems to be a bug with react-i18next, the hook is imported from that package.

**Comment by janhesters** [comment]
@sergiodxa Got it.

The weird thing is, there are no reports about it on `react-i18next`. So either almost no one is using `<Suspense />` or the bug originates within Remix.

```ts
https://github.com/i18next/react-i18next/issues?q=is%3Aissue+suspense
```

If I find the time to learn how to use `<Suspense />` without Remix, I'll try and see if it also happens with normal React.

**Comment by mjsol12** [comment]
Hi, I'm intrigued about the outcome of this bug, currently implementing the package but I have concerns regarding how will impact my future suspense implementation.

**Comment by harshal-99** [comment]
> The weird thing is, there are no reports about it on `react-i18next`. So either almost no one is using `<Suspense />` 

or people could be using `getFixedT` to translate it on the server

another solution I found was to defer running t from  useTranslation hook

```tsx
const Component = () => {
const {t} = useTranslation();

return <div>{t('key')}</div>
}
```
above code will crash

```tsx
const Component = () => {
const {t} = useTranslation();
const [trans, setTrans] = useState('')
useEffect(() => {
  setTrans(t('key'))
}, [])
return <div>{trans}</div>
}
```
above code will not work if you are Streaming 
so it seems `getFixedT` is the only option we have for now


I will try to learn how to use `<Suspense />` without remix and try to recreate same problem with react

**Comment by harshal-99** [comment]
Hey @janhesters I could not recreate this bug, my issue was resolved when I set ```{react: {useSuspence: true}}``` in `i18n.js`

most likely i18n was misconfigured

**Comment by rjvim** [comment]
hey @janhesters

Were you able to resolve the above issue, whenever I use Remix with Streaming, and if there is a route with `<Suspense...` it shows "This Suspense boundary received an update before it finished hydrating."

cc: @harshal-99 In your example, did u have route similar to in the description? Also is it Remix which is Stream. 

Please let me know.

**Comment by janhesters** [comment]
@rjvim Sorry, this has been so many months ago, that I do not remember the context anymore.

**Comment by rjvim** [comment]
Hey @janhesters No problem.

Will try to remind it.

In Remix whenever we use something like following:

```
      <Suspense fallback={<p>Loading package location...</p>}>
        <Await
          resolve={data.nonCricital}
          errorElement={<p>Error loading package location!</p>}
        >
          {nonCricital => <p>{nonCricital}</p>}
        </Await>
      </Suspense>
```

We get an error like following:

<img width="1013" alt="Screenshot 2024-01-04 at 17 38 35" src="https://github.com/sergiodxa/remix-i18next/assets/23579455/b22c1063-3a9e-4044-b184-21ec81867015">

And this happens only "I18nextProvider" provider is used even with `useSuspense: false` or `useSuspense: true`

It's not clear if this issue was ever fixed.

**Comment by sergiodxa** [comment]
All of those hooks and components come from react-i18next, I recommend you to open an issue on the react-i18next repository.
