### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by juniorforlife** [sergiodxa/remix-i18next#138]
### Describe the bug

This seems that this error only happens when I update some static text with `t` from `const {t} = useTranslation()`.

I notice when I remove `responseHeaders.set("Content-Type", "text/html");` in `entry.server.tsx` as mentioned [here](https://github.com/sergiodxa/remix-i18next#server-side-configuration), then the error goes away.
However I'm not sure if this "fix" is gonna break anything else. Hopefully someone can help me figure this out

### Your Example Website or App

sorry the website is not deployed yet

### Steps to Reproduce the Bug or Issue

1. Replace some static text with `t("someKey")`
2. The UI doesn't get updated
3. Do a hard reload
4. Error happens
5. Restart dev server
6. It works

### Expected behavior

There shouldn't be any error 

### Screenshots or Videos

https://github.com/sergiodxa/remix-i18next/assets/68360917/ca2d207d-e40c-475d-b092-13ab18a58568

### Platform

- OS: macOS
- Browser: Firefox
- Version: remix 1.16.1, remix-i18next: 5.1.1

**Comment by nadaaskora** [comment]
I have the same issue and tested it on Safari and worked fine
