### ISSUE TITLE
backend translation not working

### ISSUE THREAD

**Issue by Neji-5O** [sergiodxa/remix-i18next#162]
### Describe the bug

the translation in entry.server.ts is not working, like the client version make the translation work but the problem is take one or 2 second in show and that is not good for UX

### Your Example Website or App

localhsot

### Steps to Reproduce the Bug or Issue

translations is coming from api and not local, same config like the doc here, and remix v2

### Expected behavior

to have translation in back end entry.server.ts

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
ubuntu
chrome

**Comment by Neji-5O** [comment]
resolved i figure it out the problem
FYI for react i18 next make sure the back end part to explicitly add full url to api :D

**Comment by VityaSchel** [comment]
> resolved i figure it out the problem FYI for react i18 next make sure the back end part to explicitly add full url to api :D

I have exact same problem, how did you fix it? wdym full url to api
