### ISSUE TITLE
react-i18next 14 support

### ISSUE THREAD

**Issue by stevensacks** [sergiodxa/remix-i18next#170]
### Describe the bug

react-i18next peer dependency is 13.5.

14.x is out now which resolves the casting issue.

https://github.com/i18next/react-i18next/issues/1693

### Your Example Website or App

https://github.com/i18next/react-i18next/issues/1693

### Steps to Reproduce the Bug or Issue

```
found 0 vulnerabilities
npm WARN Could not resolve dependency:
npm WARN peer react-i18next@"^13.0.0" from remix-i18next@5.4.0
npm WARN node_modules/remix-i18next
npm WARN   remix-i18next@"5.4.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: hafh-front-end-v2@0.0.1
npm WARN Found: react-i18next@13.5.0
npm WARN node_modules/react-i18next
npm WARN   peer react-i18next@"^13.0.0" from remix-i18next@5.4.0
npm WARN   node_modules/remix-i18next
npm WARN     remix-i18next@"5.4.0" from the root project
```

### Expected behavior

Update peer dep to 14.x.

### Platform

- OS: n/a
- Browser: n/a
- Version: n/a

**Comment by sergiodxa** [comment]
Done in the latest release
