### ISSUE TITLE
SSR does not work

### ISSUE THREAD

**Issue by VityaSchel** [sergiodxa/remix-i18next#173]
### Describe the bug

All translations are loaded 1s after page load
Can you please help? I tried everything

### Your Example Website or App

https://github.com/VityaSchel/session-bots-directory

### Steps to Reproduce the Bug or Issue

1. Run project
2. translations are not generating server side and it cause a lot of hydrate errors

### Expected behavior

I expect SSR

### Platform

- OS: macOS
- Browser: Chrome
- Version: 5.5.0

**Comment by sergiodxa** [comment]
It seems you have [`handle` export in your root](https://github.com/VityaSchel/session-bots-directory/blob/36df6fa3be773122bc08bf2b94ba912e265b4c65/app/root.tsx#L27-L29) but not in other routes and you're using other namespaces.

If you do that remix-i18next can't preload the namespaces your app will use.
