### ISSUE TITLE
On demand namespaces doesn't load

### ISSUE THREAD

**Issue by viclafouch** [sergiodxa/remix-i18next#195]
### Describe the bug

Following this discussion : https://github.com/sergiodxa/remix-i18next/discussions/171

Looks like it's an issue :/

> Hello there! I was using this integration with multiple namespaces to load them only where are needed, but when I go to another page via remix links, the json file doesn't load and the UI shows the raw keys, any idea of why?

What's the solution ? 

### Your Example Website or App

/

### Steps to Reproduce the Bug or Issue

Example : 
* Route 1 : `export const handle = { i18n: ['checkUp'] }`
* Route 2 : `export const handle = { i18n: ['home'] }`
* Route 3 : `export const handle = { i18n: ['followUp'] }`

You hardreload on Route 1, you have your correct namespaces / translations. But If I go on the Route 2, then `getInitialNamespaces` function from `remix-i18next/client` is not executed again.. So we all of the keys are not translated.. 

### Expected behavior

If you go on Route 2 from Route 1, your namespaces must be loaded first.

### Screenshots or Videos

No screenshots

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by sergiodxa** [comment]
Are you setting the namespace in `useTranslation` hook from react-i18next?

**Comment by viclafouch** [comment]
Yep, I'm doing this `const { t } = useTranslation(['checkup', 'common'])`

Doesn't change anything :/

**Comment by viclafouch** [comment]
Ooo I find, it was `checkUp` and no `checkup`.

BUT, now, it's working, but there is a flink between the key and the text behind.. 


https://github.com/sergiodxa/remix-i18next/assets/23353836/d30f90a0-908e-4fa0-998d-7fb22bb3f54c

Do you have an idea ? :)

**Comment by sergiodxa** [comment]
If you're fetching the translations from a service I would cache that
If your translations are deployed along your app I would load them immediately since there's no benefit of on-demand load server-side

**Comment by viclafouch** [comment]
OK perfect thanks !
