### ISSUE TITLE
6.2.0 broke typed locale files

### ISSUE THREAD

**Issue by stevensacks** [sergiodxa/remix-i18next#202]
### Describe the bug

Something in remix-i18next 6.2.0 broke something with typescript typed language files and now keys in the `t` function returned by `i18next.getFixedT()` throw TS errors if you don't include `keyPrefix` in the `getFixedT()` options. It's still working at runtime, the keys are returning their values. But, TypeScript complains inside the `t()` function. Adding the `keyPrefix` option makes the TS error go away.

**TS Error**
![no keyPrefix causes typescript error](https://github.com/user-attachments/assets/bacf6e3c-3a69-424c-ac61-d374826ddf75)

**With KeyPrefix**
![only way to resolve typescript error](https://github.com/user-attachments/assets/a9c7d57d-c4cd-4c22-8895-4f662bdc21e9)

---

There is also a TS error if you do not include the namespace(s) param to `getFixedT()` and instead pass the `ns` as an option in `t()`, where the `keyPrefix` option is not available. I have not figured out a way to resolve this one. Again, the string values are still returned correctly at runtime, but TypeScript has an error.

![ns option also has error](https://github.com/user-attachments/assets/a6ad7a91-9777-46a6-891d-90a2b0929ec6)

### Your Example Website or App

https://stackblitz.com/edit/remix-run-remix-qazht2

### Steps to Reproduce the Bug or Issue

Stackblitz unfortunately appears to not read in `*.d.ts` files in the project, so you cannot reproduce this issue in stackblitz because it doesn't apply any typing to i18next keys at all. Everything else in the project is set up in Stackblitz.

Adding typing is as simple as adding a type definition file `i18next.d.ts` to your project, as per [their documentation](https://www.i18next.com/overview/typescript#create-a-declaration-file).

```ts
import type resources from '~/languages/en';

declare module 'i18next' {
  interface CustomTypeOptions {
    resources: typeof resources;
  }
}
```

This works as expected outside of Stackblitz. I couldn't figure out how to get it to work in Stackblitz. If you know how, you should be able to turn that on and reproduce the issue.

### Expected behavior

Prior to 6.2, the types were correctly identifying the namespaces and key paths. Now, they're broken as described above.

### Platform

- OS: macOS
- Browser: N/A
- Version: N/A

### Additional context

Rolling back to remix-i18next v6.1.1 fixes the issue.

**Comment by davidesigner** [comment]
Hi @sergiodxa,

Same error here with 6.2.1 (only with the `getFixedT` method, the `useTranslation` method is working as before):
<img width="1470" alt="Screenshot 2024-08-06 at 23 21 42" src="https://github.com/user-attachments/assets/e311dee8-a0f8-4c34-8a21-d70f8254ddf3">

I can "solve" the problem by defining the namespace as the second argument to the `t` function (but this is not the intended use):
<img width="470" alt="Screenshot 2024-08-06 at 23 23 18" src="https://github.com/user-attachments/assets/48d1dc0e-5fff-4759-97f7-70d6cc657b0a">

N.B. I have the same typing definition as @stevensacks:
```ts
import { type resources, type defaultNS } from '~/app/locales/i18n.ts';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: typeof defaultNS;
    resources: typeof resources.fr;
  }
}
```

**Comment by sergiodxa** [comment]
I added typed namespaces to the getFixedT tests and confirmed that now it should work in v6.3.0

**Comment by davidesigner** [comment]
I confirm that is working well, thanks a lot for reactivity!
