### ISSUE TITLE
The package may have incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by tptodorov** [sergiodxa/remix-i18next#205]
### Describe the bug

Following the guide https://remix.run/resources/remix-i18next and implementing this on a new remix project, I get the following error when importing the module. 

`import { RemixI18Next } from "remix-i18next";`

---

`2:13:35 PM [vite] Error when evaluating SSR module /app/entry.server.tsx:
|- Error: Failed to resolve entry for package "remix-i18next". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "remix-i18next" package
    at packageEntryFailure 
`

### Your Example Website or App

not available

### Steps to Reproduce the Bug or Issue

Follow the tutorial https://remix.run/resources/remix-i18next

### Expected behavior

Should import the module without an error.

### Platform

- OS: Mac
- Browser: Arc
- Version:     "remix-i18next": "^6.2.1",

**Comment by sergiodxa** [comment]
Here's an example working app https://github.com/sergiodxa/remix-vite-i18next, double check your setup with the code there.
