### ISSUE TITLE
react-i18next 15 support

### ISSUE THREAD

**Issue by kenn** [sergiodxa/remix-i18next#206]
### Describe the bug

react-i18next released v15 last month.

https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md

### Your Example Website or App

https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md

### Steps to Reproduce the Bug or Issue

```sh
% pnpm outdated
┌───────────────┬──────────────────────────────────┬────────┐
│ Package       │ Current                          │ Latest │
├───────────────┼──────────────────────────────────┼────────┤
│ react-i18next │ 14.1.3                           │ 15.0.1 │
└───────────────┴──────────────────────────────────┴────────┘
```

### Expected behavior

Update dep to 15.

### Platform

- OS: n/a
- Browser: n/a
- Version: n/a

**Comment by sergiodxa** [comment]
Supported since v6.1.1, see https://github.com/sergiodxa/remix-i18next/releases/tag/v6.1.1

**Comment by kenn** [comment]
Oh didn't realize that — thank you!
