### ISSUE TITLE
Intermittent `RangeError: Incorrect locale information provided` in `i18next.getLocale(request)`

### ISSUE THREAD

**Issue by kenn** [sergiodxa/remix-i18next#209]
### Describe the bug

From time to time, I'm getting the following error at this line: `let lng = await i18next.getLocale(request)`

I have no idea how to debug this, let me know if you want me to set something up to debug the issue.

```ts
RangeError: Incorrect locale information provided
    at Function.supportedLocalesOf (<anonymous>)
    at getClientLocales
```

Here's a screenshot from Sentry:

![Screenshot 2024-09-03 at 19 12 44](https://github.com/user-attachments/assets/6262be8d-6b70-496c-9c40-fb15a40b3bee)

### Your Example Website or App

https://gista.co/

### Steps to Reproduce the Bug or Issue

Set up as README along with `i18n.ts` configured as follows:

```ts
export default {
  supportedLngs: ['en', 'ja'],
  fallbackLng: 'en',
  defaultNS: 'common',
  react: { useSuspense: false },
}
```

### Expected behavior

No error

### Platform

From Sentry:

![Screenshot 2024-09-03 at 19 10 12](https://github.com/user-attachments/assets/5e6bb5e3-de29-4824-abe8-38d5fe012a82)

**Comment by jansedlon** [comment]
I think it relates to my issue #207

**Comment by jansedlon** [comment]
@kenn I have made a PR that should fix it
