### ISSUE TITLE
React Router 7 support?

### ISSUE THREAD

**Issue by 4FunAndProfit** [sergiodxa/remix-i18next#220]
### Describe the bug

Hello, 

For now, it seems like this package (which is an amzing work), is not adapted in his code and dpeendencies for RR7/remixv3 which will be available really soon (some pre packages are available),

### Your Example Website or App

https://reactrouter.com/dev/docs/upgrading/remix

### Steps to Reproduce the Bug or Issue

Are you planning to make this package work with RR7? 

Thanks a lot in advance,

### Expected behavior

Should be compatible with RR7

### Platform

N/A

**Comment by sergiodxa** [comment]
Once it's stable yes, but since that will require a new major release I don't plan to support it before that.

**Comment by 4FunAndProfit** [comment]
Thanks @sergiodxa :) 
So I will Wait for stable version haha

**Comment by chinfeng** [comment]
[client.ts#L11](https://github.com/sergiodxa/remix-i18next/blob/main/src/client.ts#L11)，`window.__remixRouteModules` deprecated after rr7

**Comment by AlemTuzlak** [comment]
Added a PR, a pre-release/or any other kind would be awesome!

**Comment by AlemTuzlak** [comment]
Here is a temporary release until Sergio drops full support:

`npm i https://pkg.pr.new/AlemTuzlak/remix-i18next@047de17`

**Comment by AlemTuzlak** [comment]
I am like your Remix fairy, I go around and add rr7 support to packages @4FunAndProfit 😂

**Comment by AlemTuzlak** [comment]
@4FunAndProfit I actually don't, I built my own package based on theirs and added extra features on top, check out forge42/seo-tools

**Comment by 4FunAndProfit** [comment]
@AlemTuzlak But it's even better haha ❤️🧚 thanks a lot 🧚🧚🧚🧚

**Comment by 4FunAndProfit** [comment]
@sergiodxa , @AlemTuzlak I don't know if it comes from me or from this update, but when i try it with pnpm run dev i have : 
```
Sourcemap for "node_modules/.pnpm/remix-i18next@7.0.0_i18next@23.16.8_react-i18next@15.1.1_i18next@23.16.8_react-dom@18.3.1_rea_qjyeej6azlsw3lszggdw3rpadm/node_modules/remix-i18next/build/react.js" points to missing source files
``` and then Optimize Deps does not work anymore (a lot of errors from it)

Do you have the same or an idea why ? :)
