### ISSUE TITLE
entry.client.tsx getInitialNamespaces - Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mikericher** [sergiodxa/remix-i18next#228]
### Describe the bug

Upgraded remix to latest in prep for rr7. Including updating remix-i18next to 7.0.0 from 6.4.1.
6.4.1 is OK
7.0.0 causes the following error in the browser console:

Uncaught (in promise) TypeError: Cannot convert undefined or null to object

tracing back to getInitialNamespaces() in the entry.client.tsx hydrate function

Running through that function window.__reactRouterRouteModules is undefined
(Most likely due to changes with the latest remix release.
Workaround: switched the ns: getInitialNamespaces() call to ns: ['translation'] for now.

remix-i18next   7.0.0
@remix-run/*   2.15.0
i18next             24.0.2
i18next-fs-backend  2.6.0
i18next-http-backend 3.0.1

### Your Example Website or App

None

### Steps to Reproduce the Bug or Issue

hydrate function in entry.client.tsx with the above package versions:

const i18nConfig = {
  reportNamespaces: [],
  supportedLngs: ["en", "fr"],
  fallbackLng: "en",
  defaultNS: "common",
  react: { useSuspense: true }
}

await i18next
    .use(initReactI18next) 
    .use(LanguageDetector) 
    .use(Backend) 
    .init({
      reportNamespaces: [],
      supportedLngs: ["en", "fr"],
      fallbackLng: "en",
      defaultNS: "common",
      react: { useSuspense: true },
      ns: getInitialNamespaces(),
      // ns: ["common"], <-- switch to this works fine
      backend: { loadPath: "/locales/{{lng}}/{{ns}}.json" },
      detection: {
        order: ["htmlTag"],
        lookupCookie: '__locale',
        caches: [],
      },
    })

### Expected behavior

I'd expect the getInitialNamespaces() to return a list of the route namespaces

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kristijantomic** [comment]
Hi, 

I am facing the same issue as described above. I see __remixRouteModules is defined, while _reactRouterRouteModules is undefined.

```jsvascript

 window._reactRouterRouteModules
undefined

window.__remixRouteModules
{root: Module, routes/home/route: Module }
```

remix-i18next: 7.0.0
@remix-run/dev: 2.15.0
i18next: 24.0.2
i18next-fs-backend: 2.6.0
i18next-http-backend: 3.0.1

Thank you for your awsm work!

@mikericher thank you for the quick fix.

**Comment by mateusnc** [comment]
Hi,

I ran into the same issue, and after some digging, I found out that remix-i18next v7 [only works with React Router v7](https://github.com/sergiodxa/remix-i18next/issues/225#issuecomment-2495132400).

Since a lot of libraries still don’t support React Router v7, I decided to downgrade remix-i18next to v6.4.1 for now.

**Comment by sergiodxa** [comment]
Yes, remix-i18next v7 only works with RRv7, if you're still on Remix keep using remix-i18next v6
