### ISSUE TITLE
Release version with i18next v24

### ISSUE THREAD

**Issue by ondrejsevcik** [sergiodxa/remix-i18next#229]
Hi, I've noticed that the repo is updated currently with the latest version of i18next, but it is not released. Would it be possible to make another release? It would make our life much easier. Thank you

https://github.com/sergiodxa/remix-i18next/blob/f88e4c92148010ccd3baa0db849d3c8b6ddfdd39/package.json#L31

**Comment by justb3a** [comment]
yes please 🙏 🙏 🙏 

I cannot update because of peer dependency issues. 

```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: app@1.0.0
npm error Found: i18next@24.0.5
npm error node_modules/i18next
npm error   i18next@"24.0.5" from the root project
npm error
npm error Could not resolve dependency:
npm error peer i18next@"^23.1.0" from remix-i18next@7.0.0
npm error node_modules/remix-i18next
npm error   remix-i18next@"7.0.0" from the root project
```

**Comment by sergiodxa** [comment]
Released https://github.com/sergiodxa/remix-i18next/releases/tag/v7.0.1
