### ISSUE TITLE
Warning on updating sessionStorage cookie

### ISSUE THREAD

**Issue by edmbn** [sergiodxa/remix-i18next#32]
When updating the sessionStorage cookie I'm getting the following warning:

`Warning: Cannot update a component (`NavigationLinks`) while rendering a different component (`App`).`

It happens when submitting a form and inside the action I update the sessionStorage:

>       const languageSession = await getLanguageSession(request);
>       languageSession.setLanguage(language);
>       return json(
>         { headers: { "Set-Cookie": await languageSession.commit() } }
>       );

The problem always come from the "layout page", which is a sidebar.

**Comment by sergiodxa** [comment]
That looks like an error with Remix, this packages doesn't do anything with the sessionStorage aside of reading the language if provided, the sessionStorage object it's still handled by your and Remix.

**Comment by edmbn** [comment]
Well yeah... I don't think the problem comes from sessionStorage either. It clearly logs that the error comes from useTranslation hook.

**Comment by sergiodxa** [comment]
> Well yeah... I don't think the problem comes from sessionStorage either. It clearly logs that the error comes from useTranslation hook.

The useTranslation hook comes from react-i18next and is not touched by remix-i18next

**Comment by edmbn** [comment]
For anyone having the same issue it looks like it was an issue with the remix-i18next package and was solved on #27. On tag 2.2.0 this is working as expected.
