### ISSUE TITLE
How could I use remix-i18next inside my CatchBoundary and ErrorBoundary placed at root.ts

### ISSUE THREAD

**Issue by doncicuto** [sergiodxa/remix-i18next#33]
Hi,
I've tried to use useTranslation inside my CatchBoundary and ErrorBoundary placed at my root.ts so I could translate some of the text messages, but I can't. What would be the best strategy to use translations inside my boundaries in root.ts and in some other routes?  

Thanks in advance

**Comment by sergiodxa** [comment]
For boundaries inside `root` it's not possible right now, maybe there could be some hacky way, but I'm not aware.

For boundaries in other routes, load their translations in the root or another parent route and it should work.

**Comment by doncicuto** [comment]
Thanks a lot for your answer. Closing.
