### ISSUE TITLE
Loop when using fetcher.load inside a component

### ISSUE THREAD

**Issue by doncicuto** [sergiodxa/remix-i18next#34]
Hi, I'm having a bad time trying to understand what I'm doing wrong. I've been using remix-i18n successfully but a week ago I encountered a problem when I wanted to have some components that would use fetcher.load to get some information, I had a nasty loop. I first thought that I wasn't using fetcher and useEffect properly so after checking many things and asking for some help in Discord I started with a minimal repository.

I created a route index that used a component that retrieved information from a route loader (/api/test) and all worked fine. Then I followed remix-i18n readme to add it to the repo and I started to see the same problem. It seems there's a loop and you can check my issue in this sandbox: https://codesandbox.io/s/delicate-snowflake-uzwgw or cloning this repo: https://github.com/doncicuto/issue-fetcher-i18n
 
I do feel that as noob maybe I'm not understanding the issue, but I can't find a way to debug it, so I hope you can help me. 

Thanks in advance

**Comment by viczam** [comment]
Indeed, I bumped into this issue too.

```tsx
import i18next from 'i18next';
import { hydrate } from 'react-dom';
import { initReactI18next } from 'react-i18next';
import { RemixBrowser } from 'remix';
import { RemixI18NextProvider } from 'remix-i18next';
import { LOCALES } from './config';

i18next
  .use(initReactI18next)
  .init({
    supportedLngs: LOCALES,
    defaultNS: 'main',
    fallbackLng: 'en',
    react: { useSuspense: false },
  })
  .then(() => {
    return hydrate(
      <RemixI18NextProvider i18n={i18next}>
        <RemixBrowser />
      </RemixI18NextProvider>,
      document,
    );
  });
```

If I remove this part - `<RemixI18NextProvider i18n={i18next}>` - all goes back to normal.

**Comment by sergiodxa** [comment]
Could you check if this still happens with v4.0.0?

**Comment by viczam** [comment]
It works fine with v4.0.0.
