### ISSUE TITLE
Locale paths and changing language

### ISSUE THREAD

**Issue by esonesson** [sergiodxa/remix-i18next#35]
Hey, I'm testing out with Remix and remix-i18next for a project.

Trying to figure out how this can be used with locale paths, for example: `site.com/en` to get the english translated page, and `site.com` to get the default locale. Is this possible?

And do you have an example on how a locale switcher would work?

**Comment by matmilbury** [comment]
It's possible, we've implemented something like this on https://www.tenset.io/

**Comment by larissa-n** [comment]
Some recent projects out there with more ideas for how to implement local paths:

- https://github.com/derhub/remix-rosetta-i18n - very simple implementation that basically uses window.location.pathname.slice(0, 4).replace(/\/+$/, '') === '/en'
- https://github.com/AnandChowdhary/remix-starter - en-us notation, also checks IP-based location as a fallback

It would be great if `remix-i18next` could support localized routing in the future!

**Comment by matmilbury** [comment]
@larissa-n thanks! There is a lot to it but the main parts are as follows:

In `root.tsx`, we check for if the pathname equals `/` and if yes, we redirect to user's default locale with `no-cache` directive. Something like this:

```tsx
export const loader: LoaderFunction = async ({ request }) => {
  const locale = detectLocale(request)

  const url = new URL(request.url)
  if (url.pathname === '/') {
    return redirect(`/${locale}`, {
      status: 301,
      headers: { 'Cache-Control': 'no-cache' },
    })
  }

  return null
}
```

As you noticed, we have this `detectLocale` function. What it does is it takes the first segment of the pathname and tries to mach it with supported locales. If no luck there, it parses `Accept-Language` header with `accept-language` npm library.

Then we have `$locale.tsx` file pretty much as `remix-starter` you linked.

For links, we have `useLocalizePathname` hook, that returns a function that prefixes paths with current locale.

For building a language switcher, see https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#accessibility

Hope it gives you some ideas to get started with your implementation!

**Comment by larissa-n** [comment]
Thanks for sharing your approach, @matmilbury ! I like it! Good idea to use a hook for localizing links, that's definitely important if the locale is part of the pathname.

We're also using the loader function to detect the locale and then serve that content. We don't check for `Accept-Language` but just go by the host name / domain. Our `detectLanguage(request)` uses `request.url` and goes through a list, similar to internationalized routing in nextjs.

We ended up not using i18next but just created a react context that works much the same way. Our rationale behind keeping it light on the language detection side of things is that most people enter our site through Google and they already land on the language they prefer, although their browser settings may not align (some visitors use mobile devices and have never changed the browser language from English to whatever it is they actually prefer, but thanks to search engines it's easy to enter the site on the preferred language, so we chose not to take that control away from them).

@esonesson In terms of locale switcher, we created a menu with actual links (to help Bing's bots, which don't seem to render javascript). Looks like that's what you guys did as well @matmilbury. Here's a basic implementation:
```
<div className="dropdownItems">
   {otherLangs.map(l => (
       <a href={"https://www." + l.domain + (pathname || '')} key={l.key}>{l.string}</a>
    ))}
</div>
```

**Comment by sergiodxa** [comment]
> Hey, I'm testing out with Remix and remix-i18next for a project.
> 
> Trying to figure out how this can be used with locale paths, for example: `site.com/en` to get the english translated page, and `site.com` to get the default locale. Is this possible?
> 
> And do you have an example on how a locale switcher would work?

Since you get the locale from the URL, you can create a `routes/$lng` file and folder use `params.lng` to detect the language. Then use that as locale for the rest of the app.
