### ISSUE TITLE
support cloudflare page

### ISSUE THREAD

**Issue by punkyoon** [sergiodxa/remix-i18next#36]
I tried to apply this lib for my personal project on cloudflare page. but It doesn't work with this error:

```bash
$ npm run start

> start
> npm run dev:wrangler

> dev:wrangler
> wrangler pages dev ./public --watch ./build

Compiling worker to "/var/folders/3s/74fw0j915232w50ctbnxyg7c0000gn/T/functionsWorker.js"...
Compiled Worker successfully.
[pages:err] TypeError: Cannot read properties of undefined (reading 'FileSystemBackend')
    at build/index.js (/Users/test/project-name/app/i18n.server.ts:5:34)
    at __init (/var/folders/3s/74fw0j915232w50ctbnxyg7c0000gn/T/functionsWorker.js:16:56)
    at functions/[[path]].js (/Users/test/project-name/functions/[[path]].js:4:1)
```

Is it available to support remix project on cloudfront?

**Comment by punkyoon** [comment]
https://github.com/sergiodxa/remix-i18next#custom-backend

sorry i found this

**Comment by punkyoon** [comment]
I found about custom backend in [README](https://github.com/sergiodxa/remix-i18next#custom-backend), so I tried to use `FetchBackend` but it also doesn't work with this error 🤔 :

```
$ npm run start

> start
> npm run dev:wrangler


> dev:wrangler
> wrangler pages dev ./public --watch ./build

Compiling worker to "/var/folders/3s/74fw0j915232w50ctbnxyg7c0000gn/T/functionsWorker.js"...
Compiled Worker successfully.
[pages:err] TypeError: import_remix_i18next2.FetchBackend is not a constructor
    at build/index.js (/Users/test/project-name/build/index.js:41:15)
    at __init (/var/folders/3s/74fw0j915232w50ctbnxyg7c0000gn/T/functionsWorker.js:16:56)
    at functions/[[path]].js (/Users/test/project-name/functions/[[path]].js:4:1)
    at __init (/var/folders/3s/74fw0j915232w50ctbnxyg7c0000gn/T/functionsWorker.js:16:56)
```

**Comment by larissa-n** [comment]
Here's a different approach: https://github.com/BenoitAverty/remix-i18n-test/blob/master/app/lib/i18n.server.ts

But keep in mind that Remix can run on Cloudflare Workers, whereas CloudFront is just a CDN (serves static content but cannot server-side render).

**Comment by sergiodxa** [comment]
I suppose by Cloudfront you mean Cloudflare? I want to add support for Cloudflare, for now you can import directly from the built files so they FileSystemBackend is not included.

**Comment by punkyoon** [comment]
oh i was confused. i meant cloudflare.

**Comment by sergiodxa** [comment]
Since v4.0.0, there's nothing in the library core that requires Node.js modules, so it should work just fine in Cloudflare.

**Comment by vladinator1000** [comment]
Does anyone know where I can find examples of how to set up a non-fs backend for Cloudflare Workers?

**Comment by sergiodxa** [comment]
> Does anyone know where I can find examples of how to set up a non-fs backend for Cloudflare Workers? Do I need to implement my A fetch back end of my own?

First, try to open a new issue instead of reviving an old one

Now about your question, there are multiple backends, if your translations lived within your app code, I recommend you to import them and pass them to the i18next config, this will also be faster as you already have them in memory.

If you need to load them from somewhere else, I recommend you to use the fetch backend.
