### ISSUE TITLE
Reload pages

### ISSUE THREAD

**Issue by nkrmr** [sergiodxa/remix-i18next#39]
May be have made a bad configuration but when i follow the setup from the read.me file my application reload entirely on each route and when i prefetch pages. Can you help me ?

**Comment by nkrmr** [comment]
I don't understand where i have to add the file and why the module doesn't work without reload !

**Comment by vmorenog** [comment]
> I don't understand where i have to add the file and why the module doesn't work without reload !

I just wrote a comment on the mentioned issue, take a look: https://github.com/sergiodxa/remix-i18next/issues/29#issuecomment-1043241540

**Comment by sergiodxa** [comment]
This is fixed on v4.0.0
