### ISSUE TITLE
Bug on getLocale

### ISSUE THREAD

**Issue by federicogfernandez** [sergiodxa/remix-i18next#40]
Hi,

It looks like accept-language-parser library doesn't work well for all the cases.
I have this configuration
supportedLanguages: ['es-AR', 'es-MX']
fallbackLng: 'es-AR'

When i try to set 'es-MX' (by qeury param for example), it always returns 'es-AR'
i think it returns the first match (es) without checking the whole string

**Comment by adrai** [comment]
Could be fixed with #45 45

**Comment by federicogfernandez** [comment]
Awesome! thanks
