### ISSUE TITLE
`i18n.languages were undefined or empty` after updating to v3.0.0

### ISSUE THREAD

**Issue by hauptrolle** [sergiodxa/remix-i18next#50]
### Describe the bug

After updating to version 3.0.0 i get the following warning in the browser console: `i18n.languages were undefined or empty`

### Your Example Website or App

https://github.com/sergiodxa/remix-i18next/compare/v2.3.0...v3.0.0

### Steps to Reproduce the Bug or Issue

Follow the compare changelog

### Expected behavior

I would like to have no warnings

### Platform

- OS: macOS
- Browser: Chrome
- Version: 98.0

**Comment by sergiodxa** [comment]
@hauptrolle could you provide a reproduction? I'm using the v3 on prod without this issue.

If you can, provide the reproduction with your v2 setup and the v3 upgrade so I can see what you changed, it sounds like something went wrong there.
